version: '3'

services:
  nginx:
    build: images/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/public
  php:
    build: images/php
    volumes:
      - ./:/var/www/html
    command: php-fpm
    links:
      - db
    ports:
      - "9000:9000"
    environment:
      DB_PORT: ${DB_PORT}
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./images/postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
